### ISSUE TITLE
merge into ceph-rust

### ISSUE THREAD

**Issue by cholcombe973** [ArtemGr/rados.hi.rs#2]
This is great work! I've been working on a very similar aio setup using libffi. I've been stuck trying to figure out how to unpark the task.  Would you consider PRing your work back into ceph-rust?

**Comment by ArtemGr** [comment]
Why, thanks for the praise, I appreciate that!   )

> I've been working on a very similar aio setup using libffi.

That sounds interesting.

> I've been stuck trying to figure out how to unpark the task.

I think you'd just call `unpark` from a RADOS callback.

A `Mutex` is usually needed to serialize the parallel callback and parking logics.

> Would you consider PRing your work back into ceph-rust?

Yeah, I've thought about it. I have already offered this driver as an example for ceph-rust, with the addendum that some implementation decisions might be different: https://github.com/lambdastackio/ceph-rust/issues/2

Thing is, I don't have a lot of time to work on these drivers, so to get results I have to make some shortcuts (this subject was also breached at https://www.reddit.com/r/rust/comments/5ke6lh/asynchronous_postgresql_driver/dbnks9q/). One of those shortcuts is working on my own to mimimize the overhead of communication ( cf. https://en.wikipedia.org/wiki/The_Mythical_Man-Month#The_mythical_man-month ), etc.

I wouldn't mind a merge but I won't have the time to be a power behind that merge. Makes sense?

**Comment by cholcombe973** [comment]
Yeah that's fine. I'm happy to maintain it.  Async IO is a big hole in the
library and I've been trying to piece together a solution in my spare time.
I think if we can get your work merged we can start saying that the library
is ready for real workloads. Not everyone wants sync io :-)

**Comment by ArtemGr** [comment]
I see!

So what do you think about the "lazy evaluation" semantics?
In https://docs.rs/futures/0.1.7/futures/ most futures do nothing until polled for the first time. That gives the programmer a kind of tight-assed control over when and what futures are run.

I think that's the point of half the https://docs.rs/futures/0.1.7/futures/ complexity, - instead of just running the futures, like some other libraries do, https://docs.rs/futures/0.1.7/futures/ leaves them dormant and lets you decide whether you'll run them in your event loop (mio), in a thread pool (the futures-cpupool crate), on your main thread (with `wait`), or whatever.

My libraries (rados.hi and pg_async) are eager, however. They have their own running engines (Ceph callbacks in rados.hi, a dedicated event loop thread in pg_async) and so they start running the future as soon as it's created. This calls for a very different set of patterns and semantic when handling them.

I'm not at all sure that the official Ceph library should stray from the normal futures behavior that way. Maybe it'll follow the "principle of least astonishment" better for the library to emulate the "normal" futures behaviour.

In fact, I'd very much like to learn more about the lazy evaluation semantics of the https://docs.rs/futures/0.1.7/futures/ and whether it is considered (by the futures architects) to be optional in a library implementation. I don't think this design decision got a proper stage light yet.

**Comment by ArtemGr** [comment]
I've started a reddit discussion there: https://www.reddit.com/r/rust/comments/5lf7p3/are_futures_lazy/

**Comment by ArtemGr** [comment]
So the reddit discussion cleared things quite a bit. Turns out we can start the futures proactively and don't sweat over it. To quote: "*Ah yes to clarify the way poll is designed right now is that the only way to guarantee that progress is made is to call poll. It doesn't mean that if you don't call poll progress won't be made, just that if you want to be sure to make progress you must call poll.*"

That's one obstacle less.

---

What remains is the logistics of the merge.

The library is by no way finished, I intend to add the asynchronous key-value operations at the very least. As I've said earlier, I need a way to work with the code without much hindrance. With this invariant in place, I see two ways of merging the code into ceph-rust:

1) I code there (in rados.hi.rs) and you port it to ceph-rust.

2) I code in ceph-rust (provided I have direct commit access there) and you adjust the code to match ceph-rust standards, if needed.

**Comment by cholcombe973** [comment]
That's interesting.  I've been back and forth about whether futures are
even a good fit for Ceph because they wrote their own polling mechanism
with callbacks.  It's up to you.  I'm fine with either way you want to
code.  I'd probably say the easier thing is to code in rados.hi.rs.  You
mentioned previously that you don't really have any time to maintain the
code after merge so it might be best to just put in a PR when you feel it's
ready and then I can take over maintaining it.  Does that seem reasonable?

Thanks!

**Comment by ArtemGr** [comment]
> You mentioned previously that you don't really have any time to maintain the code after merge

Not at all.

What I said is "*One of those shortcuts is working on my own to mimimize the overhead of communication. I wouldn't mind a merge but I won't have the time to be a power behind that merge.*".

Providing maintance and merging are different things. One has to do with bugs and feature requests, another has to do with changing style, conventions, packaging, **filing PRs** and what not.

> so it might be best to just put in a PR when you feel it's ready and then I can take over maintaining it. Does that seem reasonable?

Not in any foreseeable future. Perhaps when I abandon Ceph and Rust and become a professional scuba diver (just joking), I might just handle the code to someone else to maintain. Until then I'd like to have free access to my code and submitting it in a PR is the opposite of that.
